Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,23 +31,22 @@ jobs:
 
       - name: Create RDP User with own Password
         run: |
-          Add-Type -AssemblyName System.Security
-          $charSet = @{
-             Password   = Paw@09854726199
+         $password = "Paw@09854726199"
+                $securePass = ConvertTo-SecureString $password -AsPlainText -Force 
+            
+                if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
+                    New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
+                }
           
-          $rawPassword = @()
-          $rawPassword = $charSet.Password
-          $password = -join ($rawPassword)
-          New-LocalUser = -Name "RDP" -Password $securePass -AccountNeverExpires
-          Add-LocalGroupMember = -Group "Administrators" -Member "RDP"
-          Add-LocalGroupMember = -Group "Remote Desktop Users" -Member "RDP"
+               Add-LocalGroupMember -Group "Administrators" -Member "RDP"
+              Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
           
-          echo "RDP_CREDS=User: RDP | Password: $password" >> $env:GITHUB_ENV
+              echo "RDP_CREDS=User: RDP | Password: (stored in secrets)" >> $env:GITHUB_ENV
           
-          if (-not (Get-LocalUser -Name "RDP")) {
-              Write-Error "User creation failed"
-              exit 1
-          }
+              if (-not (Get-LocalUser -Name "RDP")) {
+                  Write-Error "User creation failed"
+                  exit 1
+              }
 
       - name: Install Tailscale
         run: |
